"""empty message

Revision ID: 8f7e75994865
Revises: 54b19e498a1d
Create Date: 2020-11-30 00:40:54.376228

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8f7e75994865'
down_revision = '54b19e498a1d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
